
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;




/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Abdelraheem Mohamed
 */
public class MainFrame extends javax.swing.JFrame {
        

    

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();

     ButtonGroup bg = new ButtonGroup();
     bg.add(malejbutt);
     
     bg.add(femalejbutt);
     femalejbutt.setSelected(true);
     // me 

  
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JPanel malebutton = new javax.swing.JPanel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        javax.swing.JLabel email = new javax.swing.JLabel();
        javax.swing.JLabel phone = new javax.swing.JLabel();
        javax.swing.JLabel address = new javax.swing.JLabel();
        javax.swing.JButton buttadd = new javax.swing.JButton();
        javax.swing.JButton buttclear = new javax.swing.JButton();
        tffirstname = new javax.swing.JTextField();
        tfsecondname = new javax.swing.JTextField();
        tfemail = new javax.swing.JTextField();
        tfphone = new javax.swing.JTextField();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        malejbutt = new javax.swing.JRadioButton();
        femalejbutt = new javax.swing.JRadioButton();
        tfaddress = new javax.swing.JTextField();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        dateofbirth = new javax.swing.JTextField();
        javax.swing.JButton buttdelete = new javax.swing.JButton();
        txtsearch = new javax.swing.JTextField();
        javax.swing.JButton btnsearch = new javax.swing.JButton();
        javax.swing.JButton Exit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablecontacts = new javax.swing.JTable();
        combobox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard");
        setBackground(new java.awt.Color(0, 153, 204));
        setMinimumSize(new java.awt.Dimension(1183, 826));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setBackground(new java.awt.Color(255, 153, 153));
        jLabel1.setFont(new java.awt.Font("Script MT Bold", 1, 60)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contact (2).png"))); // NOI18N
        jLabel1.setText("My Contacts");

        malebutton.setBackground(new java.awt.Color(255, 51, 51));
        malebutton.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "New Contact", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        malebutton.setOpaque(false);
        malebutton.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                malebuttonAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dot.png"))); // NOI18N
        jLabel2.setText("First Name");

        email.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        email.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dot.png"))); // NOI18N
        email.setText("Email");

        phone.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        phone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dot.png"))); // NOI18N
        phone.setText("Phone");

        address.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        address.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dot.png"))); // NOI18N
        address.setText("Address");

        buttadd.setBackground(new java.awt.Color(102, 102, 255));
        buttadd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttadd.setForeground(new java.awt.Color(255, 255, 255));
        buttadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add-group.png"))); // NOI18N
        buttadd.setText("Add");
        buttadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttaddActionPerformed(evt);
            }
        });

        buttclear.setBackground(new java.awt.Color(102, 102, 255));
        buttclear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttclear.setForeground(new java.awt.Color(255, 255, 255));
        buttclear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dust.png"))); // NOI18N
        buttclear.setText("Clear");
        buttclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttclearActionPerformed(evt);
            }
        });

        tffirstname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tffirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tffirstnameActionPerformed(evt);
            }
        });

        tfsecondname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        tfemail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfemailActionPerformed(evt);
            }
        });

        tfphone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfphoneActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dot.png"))); // NOI18N
        jLabel3.setText("Second Name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dot.png"))); // NOI18N
        jLabel4.setText("Gender");

        malejbutt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        malejbutt.setSelected(true);
        malejbutt.setText("Male");
        malejbutt.setOpaque(false);
        malejbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                malejbuttActionPerformed(evt);
            }
        });

        femalejbutt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        femalejbutt.setText("Female");
        femalejbutt.setOpaque(false);

        tfaddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfaddressActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dot.png"))); // NOI18N
        jLabel5.setText("Date of Birth");

        dateofbirth.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout malebuttonLayout = new javax.swing.GroupLayout(malebutton);
        malebutton.setLayout(malebuttonLayout);
        malebuttonLayout.setHorizontalGroup(
            malebuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(malebuttonLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(buttadd, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttclear, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(malebuttonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(malebuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(malebuttonLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(49, 49, 49)
                        .addComponent(tffirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(malebuttonLayout.createSequentialGroup()
                        .addGroup(malebuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(malebuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, malebuttonLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(malejbutt, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(femalejbutt, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, malebuttonLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(malebuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfsecondname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfemail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())))
                    .addGroup(malebuttonLayout.createSequentialGroup()
                        .addGroup(malebuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(address, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(phone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(malebuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(malebuttonLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(malebuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfphone, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                                    .addComponent(tfaddress))
                                .addGap(12, 12, 12))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, malebuttonLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dateofbirth, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );

        malebuttonLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tfemail, tffirstname, tfphone, tfsecondname});

        malebuttonLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {buttadd, buttclear});

        malebuttonLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {dateofbirth, tfaddress});

        malebuttonLayout.setVerticalGroup(
            malebuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(malebuttonLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(malebuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tffirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(malebuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfsecondname, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(malebuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfemail, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(malebuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(femalejbutt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(malejbutt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(malebuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(malebuttonLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))
                    .addComponent(tfphone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(malebuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(malebuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateofbirth, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addGroup(malebuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttclear)
                    .addComponent(buttadd, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
        );

        malebuttonLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tfemail, tffirstname, tfphone, tfsecondname});

        malebuttonLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {buttadd, buttclear});

        malebuttonLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {dateofbirth, tfaddress});

        buttdelete.setBackground(new java.awt.Color(102, 102, 255));
        buttdelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttdelete.setForeground(new java.awt.Color(255, 255, 255));
        buttdelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        buttdelete.setText("Delete");
        buttdelete.setOpaque(false);
        buttdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttdeleteActionPerformed(evt);
            }
        });

        txtsearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });

        btnsearch.setBackground(new java.awt.Color(102, 102, 255));
        btnsearch.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnsearch.setForeground(new java.awt.Color(255, 255, 255));
        btnsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loupe.png"))); // NOI18N
        btnsearch.setText("Search");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        Exit.setBackground(new java.awt.Color(102, 102, 255));
        Exit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Exit.setForeground(new java.awt.Color(255, 255, 255));
        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png"))); // NOI18N
        Exit.setText("  Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        tablecontacts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Second Name", "Email", "Gender", "Phone", "Address", "Date of Birth"
            }
        ));
        tablecontacts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablecontactsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablecontacts);

        combobox.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "First Name", "Secind Name", "Email", "Gender ", "Phone ", "Address", "Date of Birth" }));
        combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(malebutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 910, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(buttdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnsearch, combobox});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(malebutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnsearch, combobox});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tffirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tffirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tffirstnameActionPerformed

    private void tfphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfphoneActionPerformed
        

    
    private boolean isValidName(String name) {
        
        return name.matches("^[a-zA-Z]+$");
    }
    
           private boolean isVlaidDate(String dateofbirth){
           String dateRegex =  "^(19|20)\\d\\d-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])$";
           return dateofbirth.matches(dateRegex);
       }
    
    private boolean isValidEmail(String email) {
    String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
    return email.matches(emailRegex);
    }
    private boolean isEgyptianPhoneNumber(String phoneNumber) {
    String phoneRegex = "^(011|012|010)\\d{8}$";
    return phoneNumber.matches(phoneRegex);
    }

    private void buttaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttaddActionPerformed
            

        String firstname = tffirstname.getText();
        String secondname = tfsecondname.getText();
        String email = tfemail.getText();
        
                String gender = "Male";
                
        if (femalejbutt.isSelected()){
            gender = "Female";
        }
        
        String phone = tfphone.getText();
        String address = tfaddress.getText();
        String date = dateofbirth.getText();

                
        
        if (firstname.isEmpty() || email.isEmpty() || phone.isEmpty() || gender.isEmpty() ||  address.isEmpty() || secondname.isEmpty() || date.isEmpty()){
            JOptionPane.showMessageDialog(this,
                    "please , Enter all information " ,
                    "Try Again",
                    JOptionPane.ERROR_MESSAGE );
        }
        else if (phone.length() != 11 || !isEgyptianPhoneNumber(phone)) {
        JOptionPane.showMessageDialog(this, "Invalid or non-Egyptian phone number. Please enter a valid Egyptian phone number.", "Try again", JOptionPane.ERROR_MESSAGE);
    } 

        else if (!isValidName(firstname)) {
            JOptionPane.showMessageDialog(this, "Invalid name",
                    "Try again", 
                    JOptionPane.ERROR_MESSAGE);
         }
                else if (!isValidName(secondname)) {
            JOptionPane.showMessageDialog(this, "Invalid name",
                    "Try again", 
                    JOptionPane.ERROR_MESSAGE);
         }
         
         else if (!isValidEmail(email)) {
        JOptionPane.showMessageDialog(this, "Invalid email address. Please enter a valid email.",
                "Try again",
                JOptionPane.ERROR_MESSAGE);
         }

         else if (! isVlaidDate(date)){
             JOptionPane.showMessageDialog(this, "Invalid dateofbirth",
                "Try again",
                JOptionPane.ERROR_MESSAGE);
        }
        
         else{
            DefaultTableModel model = (DefaultTableModel) tablecontacts.getModel();
            model.addRow(new Object[]{firstname , secondname , email , gender ,   phone , address , date });
             try {
               Class.forName("com.mysql.cj.jdbc.Driver");
              String host = "jdbc:mysql://localhost:3306/new_schema";
              String uName = "root";
              String upass = "123456";
                try (Connection con = DriverManager.getConnection(host, uName, upass)) {
                    String query = "INSERT INTO new_table8(`Fristname`, `secondname`, `email`, `Gender`, `phone`, `Address`,`Data of Brith`) VALUES (?, ?, ?, ?, ? , ?,?)";
                    PreparedStatement preparedStatement = con.prepareStatement(query);
                    preparedStatement.setString(1, firstname);
                    preparedStatement.setString(2, secondname);
                    preparedStatement.setString(3, email);
                    preparedStatement.setString(4, gender);
                    preparedStatement.setString(5, phone);
                    preparedStatement.setString(6, address);
                       preparedStatement.setString(7, date);
                    preparedStatement.execute();
                }
           
        } catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error inserting data into the database. Please check your database connection and try again.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        }
        
            tffirstname.setText("");
            tfsecondname.setText("");
            tfemail.setText("");
            tfphone.setText("");
            tfaddress.setText("");
            dateofbirth.setText("");
            
            
        // gehad and mai
    }//GEN-LAST:event_buttaddActionPerformed

    private void buttdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttdeleteActionPerformed
             int row = tablecontacts.getSelectedRow();
    if (row < 0 ){
        JOptionPane.showMessageDialog(this , "Select a row to delete" , "Try Again", JOptionPane.ERROR_MESSAGE);
    } else {
        DefaultTableModel model = (DefaultTableModel) tablecontacts.getModel();
        String Fristname = (String) model.getValueAt(row, 0);
        
        // Delete data from MySQL
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String host = "jdbc:mysql://localhost:3306/new_schema";
            String uName = "root";
            String upass = "123456";

            try (Connection con = DriverManager.getConnection(host, uName, upass)) {
                String query = "DELETE FROM new_table8 WHERE Fristname=?";
                PreparedStatement preparedStatement = con.prepareStatement(query);
                preparedStatement.setString(1, Fristname);
                preparedStatement.executeUpdate();
            }
        } catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error deleting data from the database. Please check your database connection and try again.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        // Remove the row from the local table model
        model.removeRow(row);
    } 
            //kareem
    }//GEN-LAST:event_buttdeleteActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        DefaultTableModel model = (DefaultTableModel) tablecontacts.getModel();
        Vector<Vector> tableData = model.getDataVector();
        try {
            FileOutputStream file = new FileOutputStream("file.bin");
            ObjectOutputStream output = new ObjectOutputStream(file);
            
            output.writeObject(tableData);
            output.close();
            file.close();
        }
        catch (Exception e){
            e.printStackTrace();
                
        }
        //shahd
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            FileInputStream file = new FileInputStream("file.bin");
            ObjectInputStream input = new ObjectInputStream(file);
            
            Vector<Vector> tableData = (Vector<Vector>)input.readObject();
            
            input.close();
            file.close();
            DefaultTableModel model = (DefaultTableModel) tablecontacts.getModel();
            for (int i = 0 ; i < tableData.size() ;  i++ ) {
            Vector row = tableData.get(i);
            model.addRow(new Object[]{row.get(0) , row.get(1) , row.get(2) , row.get(3) , row.get(4) , row.get(5) ,row.get(6) });
                        }
                        
        }
        catch(Exception ex){
            ex.printStackTrace();
                
            
            
        }
        //shahd
    }//GEN-LAST:event_formWindowOpened

    private void buttclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttclearActionPerformed
            tffirstname.setText("");
            tfsecondname.setText("");
            tfemail.setText("");
            tfphone.setText("");
            tfaddress.setText("");
            dateofbirth.setText("");

            //Kareem
    }//GEN-LAST:event_buttclearActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
                        String search = txtsearch.getText();
                        DefaultTableModel ob = (DefaultTableModel) tablecontacts.getModel();
                        TableRowSorter<DefaultTableModel> obj = new TableRowSorter<>(ob);
                        tablecontacts.setRowSorter(obj);
                        obj.setRowFilter(RowFilter.regexFilter(txtsearch.getText()));
                        if (search.isEmpty()){
                            JOptionPane.showMessageDialog(this ,
                                    "Please , Enter  a value to search for ! ",
                                    "Try Again",
                                    JOptionPane.ERROR_MESSAGE);
                        }
                        
                        //laila
                        
    }//GEN-LAST:event_btnsearchActionPerformed

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearchActionPerformed

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
                        DefaultTableModel ob = (DefaultTableModel) tablecontacts.getModel();
                        TableRowSorter<DefaultTableModel> obj = new TableRowSorter<>(ob);
                        tablecontacts.setRowSorter(obj);
                        obj.setRowFilter(RowFilter.regexFilter(txtsearch.getText()));
                        
                        //laila
    }//GEN-LAST:event_txtsearchKeyReleased

    private void malejbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_malejbuttActionPerformed

        
    }//GEN-LAST:event_malejbuttActionPerformed

    private void tfaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfaddressActionPerformed

    private void tfemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfemailActionPerformed
    private JFrame frame ;

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        frame = new JFrame("Exit");
        if (JOptionPane. showConfirmDialog(frame,"Confirm if you want to exit ","My Contacts ",JOptionPane.YES_NO_OPTION    )
                == JOptionPane.YES_OPTION )
        {
            System.exit(0);
        }
        //mariam
    }//GEN-LAST:event_ExitActionPerformed

    private void tablecontactsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablecontactsMouseClicked
     int rowIndex =tablecontacts.getSelectedRow();
     DefaultTableModel model=(DefaultTableModel)tablecontacts.getModel();
     
    Object genderValue = model.getValueAt(rowIndex, 3);

    if (genderValue != null) {
        String gender = genderValue.toString();

        switch (gender) {
            case "Male":
                malejbutt.setSelected(true);
                femalejbutt.setSelected(false);
                break;
            default:
                femalejbutt.setSelected(true);
                malejbutt.setSelected(false);
                break;
        }
    }
  

     tffirstname.setText(model.getValueAt(rowIndex, 0).toString());
     tfsecondname.setText(model.getValueAt(rowIndex, 1).toString());
     tfemail.setText(model.getValueAt(rowIndex, 2).toString());
     tfphone.setText(model.getValueAt(rowIndex, 4).toString());
     tfaddress.setText(model.getValueAt(rowIndex, 5).toString());
     dateofbirth.setText(model.getValueAt(rowIndex, 6).toString());
    
    }//GEN-LAST:event_tablecontactsMouseClicked

    private void comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxActionPerformed
        
    }//GEN-LAST:event_comboboxActionPerformed

    private void malebuttonAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_malebuttonAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_malebuttonAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combobox;
    private javax.swing.JTextField dateofbirth;
    private javax.swing.JRadioButton femalejbutt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton malejbutt;
    private javax.swing.JTable tablecontacts;
    private javax.swing.JTextField tfaddress;
    private javax.swing.JTextField tfemail;
    private javax.swing.JTextField tffirstname;
    private javax.swing.JTextField tfphone;
    private javax.swing.JTextField tfsecondname;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
}
